### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by g8up** [KnisterPeter/pretend#505]
Following `vscode-github` I write my own git tool for a local git service.
I got an error :
```
ReferenceError: Headers is not defined
    at prepareHeaders 
(/User/XXX/Code/oschina/gitee/node_modules/pretend/src/index.ts:70:19)
    at execute (/User/XXX/Code/oschina/gitee/node_modules/pretend/src/index.ts:111:19)
    at GiteeBlueprint.<anonymous> (/User/XXX/Code/oschina/gitee/node_modules/pretend/src/index.ts:132:14)
    at /User/XXX/Code/oschina/gitee/node_modules/pretend/src/index.ts:169:36
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```
Does Header must be set ? Where to set header ?
I set header like this:
```ts
  export class GiteeBlueprint implements Gitee {
    @Header('Accept: application/json')
    @Post('/user/repos')
    public createRepository(params: ICreateRepoParam): any { }
  }
```

**Comment by KnisterPeter** [comment]
On what environment are you? Node? Browser?
`ReferenceError: Headers is not defined` means your environment does not have a Header class and you need to provide a polyfill like https://www.npmjs.com/package/isomorphic-fetch
